services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

  indexer:
    image: qdrant/vector-db-benchmark:latest
    container_name: datavizion_indexer
    restart: on-failure
    depends_on:
      qdrant:
        condition: service_healthy
    environment:                    # must be a mapping
      QDRANT__URL: "http://qdrant:6333"
    volumes:
      - ./data_sources:/app/data_sources
      - ./config.yaml:/app/config.yaml:ro
    working_dir: /app
    command: >
      bash -c "python -u scripts/indexing/index_worker.py \
               --config /app/config.yaml \
               --once"

volumes:
  qdrant_data:
