name: Update README with version

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true    # so we can push back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Read version from version.py
        id: get_version
        run: |
          # import version.py and echo into GITHUB_ENV
          VER=$(python - <<'EOF'
import version
print(version.__version__)
EOF
)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Update README placeholder
        run: |
          # in-place replace your placeholder with ```<version>```
          sed -i "s|<!-- VERSION_PLACEHOLDER -->|```$VERSION```|" README.md

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # only commit if something changed
          if ! git diff --cached --quiet; then
            git commit -m "chore: bump README version to $VERSION"
            git push
          else
            echo "README already up-to-date, no commit necessary."
          fi
